'use strict';

/**
 * Definition of datapoints supported by the adapter.
 * Each datapoint contains metadata about the ioBroker state and the protocol mapping.
 */
const DATA_POINTS = [
  {
    id: 'power',
    channel: 'control',
    name: 'Power',
    role: 'switch.power',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'mode',
    channel: 'control',
    name: 'Mode',
    role: 'level.mode',
    type: 'string',
    write: true,
    states: {
      auto: 'auto',
      cool: 'cool',
      dry: 'dry',
      heat: 'heat',
      fanonly: 'fanonly',
      customdry: 'customdry',
    },
    pollable: true,
  },
  {
    id: 'targetTemperature',
    channel: 'control',
    name: 'Target temperature',
    role: 'level.temperature',
    type: 'number',
    unit: '°C',
    min: 16,
    max: 31,
    step: 1,
    write: true,
    pollable: true,
  },
  {
    id: 'indoorTemperature',
    channel: 'sensors',
    name: 'Indoor temperature',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'outdoorTemperature',
    channel: 'sensors',
    name: 'Outdoor temperature',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'statusCode',
    channel: 'info',
    name: 'Status code',
    role: 'value',
    type: 'number',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'statusDescription',
    channel: 'info',
    name: 'Status description',
    role: 'text.status',
    type: 'string',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'fanSpeed',
    channel: 'control',
    name: 'Fan speed',
    role: 'level.speed',
    type: 'string',
    write: true,
    states: {
      auto: 'auto',
      silent: 'silent',
      low: 'low',
      medium: 'medium',
      high: 'high',
      fixed: 'fixed',
    },
    pollable: true,
  },
  {
    id: 'swingMode',
    channel: 'control',
    name: 'Swing mode',
    role: 'level.swing',
    type: 'string',
    write: true,
    states: {
      off: 'off',
      vertical: 'vertical',
      horizontal: 'horizontal',
      both: 'both',
    },
    pollable: true,
  },
  {
    id: 'ecoMode',
    channel: 'control',
    name: 'Eco mode',
    role: 'switch.eco',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'frostProtectionMode',
    channel: 'control',
    name: 'Frost protection mode',
    role: 'switch.frostProtection',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'turboMode',
    channel: 'control',
    name: 'Turbo mode',
    role: 'switch.boost',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'sleepMode',
    channel: 'control',
    name: 'Sleep mode',
    role: 'switch.sleep',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'humiditySetpoint',
    channel: 'control',
    name: 'Humidity setpoint',
    role: 'level.humidity',
    type: 'number',
    unit: '%',
    min: 35,
    max: 85,
    step: 1,
    write: true,
    pollable: true,
  },
  {
    id: 'temperatureUnit',
    channel: 'control',
    name: 'Temperature unit',
    role: 'level.temperature',
    type: 'string',
    states: {
      celsius: 'celsius',
      fahrenheit: 'fahrenheit',
    },
    write: true,
    pollable: true,
  },
  {
    id: 'powerUsage',
    channel: 'sensors',
    name: 'Power usage',
    role: 'value.power',
    type: 'number',
    unit: 'kWh',
    readOnly: true,
  },
  {
    id: 'totalEnergy',
    channel: 'sensors',
    name: 'Total energy',
    role: 'value.energy',
    type: 'number',
    unit: 'kWh',
    readOnly: true,
  },
  {
    id: 'indoorHumidity',
    channel: 'sensors',
    name: 'Indoor humidity',
    role: 'value.humidity',
    type: 'number',
    unit: '%',
    min: 0,
    max: 100,
    readOnly: true,
  },
  {
    id: 'outdoorFanSpeed',
    channel: 'sensors',
    name: 'Outdoor fan speed',
    role: 'value.speed',
    type: 'number',
    unit: 'rpm',
    readOnly: true,
  },
  {
    id: 'defrostActive',
    channel: 'sensors',
    name: 'Defrost active',
    role: 'indicator',
    type: 'boolean',
    readOnly: true,
  },
  {
    id: 'compressorFrequencyCandidate',
    channel: 'sensors',
    name: 'Verdichterfrequenz Kandidat',
    desc: 'Kandidat: Verdichterfrequenz oder Inverter-Laststufe aus C1 Group 41 Byte 04',
    role: 'value',
    type: 'number',
    unit: 'Hz',
    readOnly: true,
  },
  {
    id: 'hotGasOrCondenserTemperatureCandidate',
    channel: 'sensors',
    name: 'Heißgas-/Kondensator-Temperatur Kandidat',
    desc: 'Kandidat: Heißgas-, Kondensator- oder Außengerät-Rohrtemperatur aus C1 Group 41 Byte 08',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'evaporatorTemperature1Candidate',
    channel: 'sensors',
    name: 'Verdampfer-Temperatur 1 Kandidat',
    desc: 'Kandidat: Verdampfer- oder Rohrtemperatur 1 aus C1 Group 41 Byte 10',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'evaporatorTemperature2Candidate',
    channel: 'sensors',
    name: 'Verdampfer-Temperatur 2 Kandidat',
    desc: 'Kandidat: Verdampfer- oder Rohrtemperatur 2 aus C1 Group 41 Byte 11',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'outdoorCoilTemperatureCandidate',
    channel: 'sensors',
    name: 'Außengerät-Rohrtemperatur Kandidat',
    desc: 'Kandidat: Außengerät-, Kondensator- oder Rohrtemperatur aus C1 Group 41 Byte 12',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'outdoorAmbientTemperatureCandidate',
    channel: 'sensors',
    name: 'Außentemperatur Group 41 Kandidat',
    desc: 'Kandidat: Außentemperatur / Außensensor aus C1 Group 41 Byte 13',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
];

module.exports = {
  DATA_POINTS,
};
