'use strict';

/**
 * Definition of datapoints supported by the adapter.
 * Each datapoint contains metadata about the ioBroker state and the protocol mapping.
 */
const DATA_POINTS = [
  {
    id: 'power',
    channel: 'control',
    name: 'Power',
    role: 'switch.power',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'mode',
    channel: 'control',
    name: 'Mode',
    role: 'level.mode',
    type: 'string',
    write: true,
    states: {
      auto: 'auto',
      cool: 'cool',
      dry: 'dry',
      heat: 'heat',
      fanonly: 'fanonly',
      customdry: 'customdry',
    },
    pollable: true,
  },
  {
    id: 'targetTemperature',
    channel: 'control',
    name: 'Target temperature',
    role: 'level.temperature',
    type: 'number',
    unit: '°C',
    min: 16,
    max: 31,
    step: 1,
    write: true,
    pollable: true,
  },
  {
    id: 'indoorTemperature',
    channel: 'sensors',
    name: 'Indoor temperature',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'outdoorTemperature',
    channel: 'sensors',
    name: 'Outdoor temperature',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'statusCode',
    channel: 'info',
    name: 'Status code',
    role: 'value',
    type: 'number',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'statusDescription',
    channel: 'info',
    name: 'Status description',
    role: 'text.status',
    type: 'string',
    readOnly: true,
    pollable: true,
  },
  {
    id: 'fanSpeed',
    channel: 'control',
    name: 'Fan speed',
    role: 'level.speed',
    type: 'string',
    write: true,
    states: {
      auto: 'auto',
      silent: 'silent',
      low: 'low',
      medium: 'medium',
      high: 'high',
      fixed: 'fixed',
    },
    pollable: true,
  },
  {
    id: 'swingMode',
    channel: 'control',
    name: 'Swing mode',
    role: 'level.swing',
    type: 'string',
    write: true,
    states: {
      off: 'off',
      vertical: 'vertical',
      horizontal: 'horizontal',
      both: 'both',
    },
    pollable: true,
  },
  {
    id: 'ecoMode',
    channel: 'control',
    name: 'Eco mode',
    role: 'switch.eco',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'frostProtectionMode',
    channel: 'control',
    name: 'Frost protection mode',
    role: 'switch.frostProtection',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'turboMode',
    channel: 'control',
    name: 'Turbo mode',
    role: 'switch.boost',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'sleepMode',
    channel: 'control',
    name: 'Sleep mode',
    role: 'switch.sleep',
    type: 'boolean',
    write: true,
    pollable: true,
  },
  {
    id: 'humiditySetpoint',
    channel: 'control',
    name: 'Humidity setpoint',
    role: 'level.humidity',
    type: 'number',
    unit: '%',
    min: 35,
    max: 85,
    step: 1,
    write: true,
    pollable: true,
  },
  {
    id: 'temperatureUnit',
    channel: 'control',
    name: 'Temperature unit',
    role: 'level.temperature',
    type: 'string',
    states: {
      celsius: 'celsius',
      fahrenheit: 'fahrenheit',
    },
    write: true,
    pollable: true,
  },
  {
    id: 'powerUsage',
    channel: 'sensors',
    name: 'Power usage',
    role: 'value.power',
    type: 'number',
    unit: 'kWh',
    readOnly: true,
  },
  {
    id: 'totalEnergy',
    channel: 'sensors',
    name: 'Total energy',
    role: 'value.energy',
    type: 'number',
    unit: 'kWh',
    readOnly: true,
  },
  {
    id: 'indoorHumidity',
    channel: 'sensors',
    name: 'Indoor humidity',
    role: 'value.humidity',
    type: 'number',
    unit: '%',
    min: 0,
    max: 100,
    readOnly: true,
  },
  {
    id: 'outdoorFanSpeed',
    channel: 'sensors',
    name: 'Outdoor fan speed',
    role: 'value.speed',
    type: 'number',
    unit: 'rpm',
    readOnly: true,
  },
  {
    id: 'defrostActive',
    channel: 'sensors',
    name: 'Defrost active',
    role: 'indicator',
    type: 'boolean',
    readOnly: true,
  },
  {
    id: 'compressorFrequency',
    channel: 'sensors',
    name: {
      en: 'Compressor frequency',
      de: 'Verdichterfrequenz',
    },
    desc: 'Verdichterfrequenz aus C1 Group 41 Byte 04. In Logs bestätigt: 0 bei Fan-only, >0 bei Kühlen/Heizen.',
    role: 'value.frequency',
    type: 'number',
    unit: 'Hz',
    readOnly: true,
  },
  {
    id: 'outdoorPipeTemperatureCandidate',
    channel: 'sensors',
    name: {
      en: 'Outdoor pipe temperature candidate',
      de: 'Außengerät-Rohrtemperatur Kandidat',
    },
    desc: 'Kandidat: Außengerät-, Kondensator- oder Rohrtemperatur aus C1 Group 41 Byte 08. Bedeutung noch nicht endgültig bestätigt.',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'indoorPipeTemperature',
    channel: 'sensors',
    name: {
      en: 'Indoor pipe temperature',
      de: 'Innengerät-Rohrtemperatur',
    },
    desc: 'Innengerät-Rohr-/Lufttemperatur aus C1 Group 41 Byte 10. Skalierung raw - 50.',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'indoorHeatExchangerTemperature',
    channel: 'sensors',
    name: {
      en: 'Indoor heat exchanger temperature',
      de: 'Innengerät-Wärmetauscher-Temperatur',
    },
    desc: 'Innengerät-Wärmetauscher-/Rohrtemperatur aus C1 Group 41 Byte 11. Fällt im Kühlbetrieb deutlich und steigt im Heizbetrieb deutlich.',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'outdoorCoilTemperatureCandidate',
    channel: 'sensors',
    name: {
      en: 'Outdoor heat exchanger temperature candidate',
      de: 'Außengerät-Wärmetauscher-Temperatur Kandidat',
    },
    desc: 'Kandidat: Außengerät-, Kondensator- oder Wärmetauscher-Temperatur aus C1 Group 41 Byte 12. Bedeutung noch nicht endgültig bestätigt.',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
  {
    id: 'outdoorTemperatureGroup41',
    channel: 'sensors',
    name: {
      en: 'Outdoor temperature Group 41',
      de: 'Außentemperatur Group 41',
    },
    desc: 'Außentemperatur aus C1 Group 41 Byte 13. Entspricht in bisherigen Logs grob dem C0-Außentemperaturwert.',
    role: 'value.temperature',
    type: 'number',
    unit: '°C',
    readOnly: true,
  },
];

module.exports = {
  DATA_POINTS,
};
